apiVersion: v1
kind: Pod
metadata:
  name: "pod-1"
  labels:
    app-name: pod-1
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-2"
  labels:
    app-name: pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - pod-1   
        topologyKey: "topology.kubernetes.io/zone"  
  containers:
  - name: nginx
    image: nginx
