apiVersion: v1
kind: Pod
metadata:
  name: "pod-1"
  labels:
    app-name: pod-demo
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-2"
  labels:
    app-name: pod-demo
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - pod-demo      
  containers:
  - name: nginx
    image: nginx
